# Generated by Django 3.1.4 on 2020-12-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
