# Generated by Django 3.1.4 on 2021-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210216_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='soeId',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
