# Generated by Django 3.1.4 on 2021-04-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210224_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
