# Generated by Django 3.1.4 on 2020-12-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenario',
            name='user_id',
        ),
    ]
