# Generated by Django 3.1.4 on 2020-12-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_remove_scenario_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='module_id',
            new_name='module',
        ),
    ]
