# Generated by Django 3.1.4 on 2020-12-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20201223_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='scenario_title',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario', to='module.module'),
        ),
    ]
