# Generated by Django 3.1.4 on 2021-01-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20210120_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='passing_score',
        ),
    ]
