# Generated by Django 3.1.4 on 2021-01-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_remove_module_passing_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='quiz_attempt',
        ),
        migrations.RemoveField(
            model_name='module',
            name='quiz_can_retake',
        ),
        migrations.AddField(
            model_name='scenario',
            name='quiz_attempt',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scenario',
            name='quiz_can_retake',
            field=models.BooleanField(default=False),
        ),
    ]
