# Generated by Django 3.1.4 on 2020-12-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='mac_ids',
            field=models.TextField(default='[]'),
        ),
    ]
