# Generated by Django 3.1.4 on 2020-12-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_config_mac_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='scenario_id',
            new_name='scenario',
        ),
    ]
