# Generated by Django 3.1.4 on 2021-01-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20201223_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='critical_points',
        ),
        migrations.RemoveField(
            model_name='config',
            name='is_owner_appeal',
        ),
        migrations.RemoveField(
            model_name='config',
            name='is_owner_at_home',
        ),
        migrations.RemoveField(
            model_name='config',
            name='is_refuse_entry',
        ),
    ]
