# Generated by Django 3.1.4 on 2021-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_auto_20210120_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
