# Generated by Django 3.1.4 on 2021-01-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_config_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='passing_score',
            field=models.FloatField(default=80.0),
        ),
    ]
